version: "3.9"

services:
  sms-service:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: sms-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - APP_ENV=docker
    volumes:
      - logs:/app/logs
    ports:
      - "8080:5005"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://sms-service:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sms-network

  sms-consumer:
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - logs:/app/logs
    environment:
      - APP_ENV=docker
    command: ["./abrarvan_challenge", "--consumer", "--queue=my_queue", "--consumer-name=worker"]
    networks:
      - sms-network
    deploy:
      replicas: 1

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms_gateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sms-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sms-network

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sms-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sms-network

volumes:
  postgres_data:
  pgadmin:
  logs:

networks:
  sms-network:
    driver: bridge